# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    cd data_structures-II/06-BST
  displayName: 'Change directory'

- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'polaris'
    polarisServerUrl: 'https://poc.polaris.blackduck.com'
    polarisAccessToken: '$(POLARIS_TOKEN)'
    polarisAssessmentTypes: 'SAST'
    polarisWaitForScan: false
    polarisApplicationName: 'Evan Onboard'
    polarisProjectName: 'C++'
    coverityBuildCommandForPolaris: 'make'