# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
 - group: SCA_Evan

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'polaris'
    polarisServerUrl: 'https://poc.polaris.blackduck.com/'
    polarisAccessToken: '$(POLARIS_TOKEN)'
    polarisAssessmentTypes: 'SAST'
    polarisProjectDirectory: 'data_structures-II/06-BST'
    polarisApplicationName: 'Evan Test'
    polarisProjectName: 'C++'

- script: |
    ls -lah /home/vsts/work/1/s/.bridge/polaris_coverity_capture
    unzip -l /home/vsts/work/1/s/.bridge/polaris_coverity_capture/idir.zip | head -100
  displayName: 'Inspect IDIR ZIP'

- script: |
    cd data_structures-II/06-BST
    directory=$(pwd)
    pip install blackduck-c-cpp
    blackduck-c-cpp -d $directory -proj "Evan" -vers "Polaris-CPP" -bd "https://expressonboarding.app.blackduck.com" -a $(AccessToken) --cov_output_dir 
  displayName: 'Install CPP tool'